---
name: Dynamic Application Security Testing

on:
  push:
    branches: [ main, feature/dast ]
  pull_request:
    branches: [ main, feature/dast ]

jobs:
  test:
    name: Run DAST using ZAP
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Build with Maven
        run: mvn package -DskipTests -Djar.finalName=sitodo
      - name: Run app
        run: java -jar target/sitodo.jar & echo $! > target/sitodo.pid
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080/'
          cmd_options: '-a -r target/site/zap/index.html'
      - name: Save test reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            target/site/zap/
          retention-days: 1
      - name: Stop app
        run: kill $(cat target/sitodo.pid)
