---
name: Dynamic Application Security Testing

on:
  push:
    branches: [ main, feature/dast ]
  pull_request:
    branches: [ main, feature/dast ]

jobs:
  test:
    name: Run DAST using ZAP
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: Run app
        run: java -jar target/sitodo-$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout).jar & echo $! > target/sitodo.pid
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080/'
          fail_action: false
          artifact_name: zap-reports
          allow_issue_writing: false
      - name: Stop app
        run: kill $(cat target/sitodo.pid)
